config/routes.rb
Rails.application.routes.draw do
  root 'tops#index'

  get "mypage", to: "mypages#index", as: :mypages

  resources :workouts, only:[:new,:create,:show,:edit,:update,:destroy]
  resources :bodies, only:[:new,:create,:show,:edit,:update,:destroy]
  
  get 'youtube/index'
  devise_scope :user do
    get "signup", to: "users/registrations#new", as: :new_user_registration
    get 'login', to: 'users/sessions#new', as: :new_user_session
    post 'login', to: 'users/sessions#create', as: :user_session
    delete 'logout', to: 'users/sessions#destroy', as: :destroy_user_session
  end

  devise_for :users, skip: [:sessions],
  controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :sex, presence: true
  validates :height, presence: true
  enum sex: { male: 0, female: 1 }

  has_many :workouts, dependent: :destroy
  has_many :bodies, dependent: :destroy
end

app/models/workout.rb
class Workout < ApplicationRecord
    belongs_to :user

    enum part: { chest: 0, shoulder: 1, stomach: 2, back: 3, arm: 4, leg: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception

    def after_sign_in_path_for(resource)
        mypages_path
    end

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:password,:height,:sex])
        end
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  before_action :authenticate_user!
  def new
    @body = Body.new
  end

  def create
    @body = current_user.bodies.build(body_params)
    height = @body.user.height / 100
    weight = @body.weight
    body_fat_percentage = @body.body_fat_percentage / 100
    @body.bmi = (weight / (height ** 2)).round(2)
    @body.lbm = (weight - (weight * body_fat_percentage)).round(1)
    if @body.save
      redirect_to mypages_path, flash:{success: "体重の記録ができました。"}
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  private
    def body_params
      params.require(:body).permit(:user_id,:date,:weight,:body_fat_percentage)
    end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(current_user.id)
    @workouts = current_user.workouts.order(id: "DESC")

    # 部位ごとの回数
    @memoData = {}
    partKeys = Workout.parts_i18n.values
    partKeys.each do |part|
      @memoData.store(part, 0)
    end
    @workouts.each do |workout|
      @memoData[workout.part_i18n] += 1
    end

    @bodies = current_user.bodies
    @weightData = {}
    @bodies.last(7).each do |body|
      @weightData.store(body.date.strftime("%m/%d"), body.weight)
    end
    @bodies = @bodies.order(id: "DESC")

    # グラフの上限・下限
    weightDataValues = @weightData.values
    @lowerLimit = weightDataValues.min
    @upperLimit = weightDataValues.max

  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :authenticate_user!

  def new
    @workout = Workout.new
  end

  def create
    @workout = current_user.workouts.build(workout_params)
    if @workout.save
      redirect_to mypages_path, flash:{success: "記録ができました。"}
    else
      render :new
    end
  end

  def show
    @workout = Workout.where(user_id: current_user.id)
  end

  def edit
  end

  def destroy
  end

  private
    def workout_params
      params.require(:workout).permit(:user_id,:date,:part,:content,:memo)
    end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  GOOGLE_API_KEY = ENV["YOUTUBE_API_KEY"]

  def find_videos(keyword, after: 1.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = GOOGLE_API_KEY

    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: 3,
      order: :date,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601
    }
    service.list_searches(:snippet, opt)
  end

  def index
    @youtube_data = find_videos('hikakin')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/helpers/youtube_helper.rb
module YoutubeHelper
end

app/views/layouts/_side_bar.html.erb
<nav>
    <header>
        筋トレ記録<i class="fas fa-hand-point-up fa-lg fa-fw"></i>
    </header>
    <div class="nav-container">
        <ul>
            <% if user_signed_in? %>
                <%= render 'layouts/user_logged_in' %>
            <% else %>
                <%= render 'layouts/user_not_logged_in' %>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/_user_logged_in.html.erb
<li>
    <%= link_to mypages_path, class: "btn-pink" do %>
        マイページ <i class="fas fa-user-alt faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

<li>
    <%= link_to new_workout_path, class: "btn-pink" do %>
        記録 <i class="fas fa-sd-card faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

<li>
    <%= link_to new_body_path do %>
        体重 <i class="fas fa-weight faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

<li>
    <%= link_to destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"} do %>
        ログアウト <i class="fas fa-sign-out-alt faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

app/views/layouts/_user_not_logged_in.html.erb
<li>
    <%= link_to new_user_registration_path, class: "btn-blue" do %>
        新規登録 <i class="fas fa-user-plus faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

<li>
    <%= link_to new_user_session_path, class: "btn-pink" do %>
        ログイン <i class="fas fa-sign-in-alt faa-ring animated-hover fa-lg fa-fw"></i>
    <% end %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkOutMemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/side_bar' %>
    <main>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            <h3><%= object.errors.count %>件のエラー</h3>
            <ul>
                <% object.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    </div>
<% end %>

app/views/shared/_login_test_user.html.erb
<%= form_with(model: User.new, url: user_session_path, local: true) do |f| %>
  <%= f.hidden_field :email, value: "test@example.com" %>
  <%= f.hidden_field :password, value: "abc123ii" %>
  <div class="btn-position">
    <%= f.submit "テストユーザーでログイン", class:"btn-green" %>
  </div>
<% end %>